### ISSUE TITLE
Request: Helm/org source of headings by ID

### ISSUE THREAD

**Issue by NathanNeff** [emacs-helm/helm-org#13]
Org-mode has a cool feature where you can assign a unique ID to a heading.  It would be cool to have a helm source which listed all headings which have an ID assigned to them.  This is a request.

**Comment by thierryvolpiatto** [comment]
To implement this, it would be nice to have details on this feature e.g. Is there a predicate telling if a heading have an ID?, which are the related functions in org where I can look at? etc...
Perhaps @alphapapa knows that and I am pretty sure he have already implemented this in one of its org packages?

**Comment by alphapapa** [comment]
Yes, this is already provided by `org-ql` and its `helm-org-ql` command.  For example:

`M-x helm-org-ql RET property:ID` would show all entries with an ID property.  The query is well-optimized and cached per-buffer.  It would not make sense to re-implement this in `helm-org`.

**Comment by thierryvolpiatto** [comment]
alphapapa <notifications@github.com> writes:

> It would not make sense to re-implement this in helm-org.

Great! Thanks.

-- 
Thierry

Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by rodrigo-morales-1** [comment]
If you don't have `org-ql` installed, you can also list all the headings in a file that contain an `ID` property by executing the following.

```elisp
(org-match-sparse-tree nil "ID={.}")
```

**Comment by alphapapa** [comment]
@rdrg109 Nice, thanks.

Closing this issue since we seem to agree there's nothing to be done here.
