### ISSUE TITLE
file-missing helm-org after upgrade to emacs-snapshot

### ISSUE THREAD

**Issue by novoid** [emacs-helm/helm-org#17]
Hi,
This could be the wrong place for this issue since I don't fully understand, what's going on:

I switched from Emacs 26.3 (Ubuntu 20.04.1 default) to Emacs snapshot `GNU Emacs 28.0.50 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.20, cairo version 1.16.0) of 2020-08-23` via https://launchpad.net/~ubuntu-elisp/+archive/ubuntu/ppa

On the first boot with `emacs --debug-init` I get:

```
Debugger entered--Lisp error: (file-missing "Cannot open load file" "No such file or directory" "helm-org")
  require(helm-org)
  byte-code("\301\302\303\304#\203\263\0\301\305!\210\306\307 \310\211\303\211\211\3:\2039\0\3\262\1\211\1A\262\2\242\262\3\211@\262\2\311\6\6\312\5!\4#\210\3..." [helm-map require helm nil noerror helm-org (lambda (def-tmp-var) (defvar helm-org-ql-map def-tmp-var "Keymap for `helm-org-ql' sessions.\nBased on `helm-...")) make-sparse-keymap ("C-x C-s" helm-org-ql-save) define-key kbd make-composed-keymap (lambda (def-tmp-var) (defvar helm-source-org-ql-views def-tmp-var "Helm source for `org-ql-views'.")) helm-make-source "Org QL Views" helm-source-sync :candidates #f(compiled-function () #<bytecode 0xad2bbbcef719ec>) :action "Show view" org-ql-view (lambda (def-tmp-var) (defvar helm-org-ql-buffers-files def-tmp-var "Used for `helm-org-ql-save'.")) make-variable-buffer-local helm-org-ql-buffers-files custom-declare-group helm-org-ql "Options for `helm-org-ql'." :group org-ql custom-declare-variable helm-org-ql-reverse-paths funcall function #f(compiled-function () #<bytecode 0x1e0000171e5d>) "Whether to reverse Org outline paths in `helm-org-..." :type boolean helm-org-ql-input-idle-delay #f(compiled-function () #<bytecode -0xd9be1ffffe8e16b>) "Seconds to wait after typing stops before running ..." number helm-org-ql-actions #f(compiled-function () #<bytecode -0x16c0a6d7a5e346b1>) "Alist of actions for `helm-org-ql' commands." (alist :key-type (string :tag "Description") :value-type (function :tag "Command")) defalias #f(compiled-function (arg1 &rest rest) "Display results in BUFFERS-FILES for an `org-ql' non-sexp query using Helm.\nInteractively, search the current buffer.  Note that this command\nonly accepts non-sexp, \"plain\" queries.\n\nNOTE: Atoms in the query are turned into strings where\nappropriate, which makes it unnecessary to type quotation marks\naround words that are intended to be searched for as indepenent\nstrings.\n\nAll query tokens are wrapped in the operator BOOLEAN (default\n`and'; with prefix, `or').\n\nFor example, this raw input:\n\n    Emacs git\n\nIs transformed into this query:\n\n    (and \"Emacs\" \"git\")\n\nHowever, quoted strings remain quoted, so this input:\n\n    \"something else\" (tags \"funny\")\n\nIs transformed into this query:\n\n    (and \"something else\" (tags \"funny\"))" (interactive #f(compiled-function () #<bytecode 0x1e000076ac81>)) #<bytecode 0x1071961b13986e58>) helm-org-ql-agenda-files #f(compiled-function () (interactive nil) #<bytecode 0x57d763310ef50ab>) helm-org-ql-org-directory ...] 11)
  require(helm-org-ql)
  eval-buffer(#<buffer  *load*-406881> nil "/home/vk/.emacs.d/config.el" nil t)  ; Reading at buffer position 159204
  load-with-code-conversion("/home/vk/.emacs.d/config.el" "/home/vk/.emacs.d/config.el" nil nil)
  load("/home/vk/.emacs.d/config.el" nil nil t)
  load-file("~/.emacs.d/config.el")
  (let ((orgfile (concat my-user-emacs-directory "config.org")) (elfile (concat my-user-emacs-directory "config.el")) (gc-cons-threshold most-positive-fixnum)) (if (or (not (file-exists-p elfile)) (file-newer-than-file-p orgfile elfile)) (progn (my-tangle-config-org))) (load-file elfile))
  eval-buffer(#<buffer  *load*> nil "/home/vk/.emacs.d/init.el" nil t)  ; Reading at buffer position 5500
  load-with-code-conversion("/home/vk/.emacs.d/init.el" "/home/vk/.emacs.d/init.el" t t)
  load("/home/vk/.emacs.d/init" noerror nomessage)
  startup--load-user-init-file(#f(compiled-function () #<bytecode 0xe33d6e794cb70eb>) #f(compiled-function () #<bytecode 0x81a386fa1b19353>) t)
  command-line()
  normal-top-level()
```

I got `org-ql-20200713.309` and `helm-org-20200311.633` via use-package and elpa as shown on https://github.com/novoid/dot-emacs/blob/master/config.org

So: either this is an issue related to `helm-org` in combination with the update or this is once again an issue related to my somewhat complex setup.

I'm switching back to 26.3 for now. If you're interested, I can provide more details if this looks promising to you. Alternatively, just close this issue.

**Comment by thierryvolpiatto** [comment]
Karl Voit <notifications@github.com> writes:

> Hi,
> This could be the wrong place for this issue since I don't fully understand, what's going on:
>
> I switched from Emacs 26.3 (Ubuntu 20.04.1 default) to Emacs snapshot GNU Emacs 28.0.50 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.20, cairo version 1.16.0) of
> 2020-08-23 via https://launchpad.net/~ubuntu-elisp/+archive/ubuntu/ppa
>
> On the first boot with emacs --debug-init I get:
>
> Debugger entered--Lisp error: (file-missing "Cannot open load file"
> "No such file or directory" "helm-org") require(helm-org)
>
> I got org-ql-20200713.309 and helm-org-20200311.633 via use-package
> and elpa as shown on
> https://github.com/novoid/dot-emacs/blob/master/config.org
>
> So: either this is an issue related to helm-org in combination with
> the update or this is once again an issue related to my somewhat
> complex setup.

Typically an issue with your config, the error message is clear, emacs
is not finding helm-org, why? I don't know, not enough infos.

> I'm switching back to 26.3 for now. If you're interested, I can
> provide more details if this looks promising to you.

Not promising, but if you need more help don't hesitate.

-- 
Thierry

**Comment by novoid** [comment]
> Typically an issue with your config, the error message is clear, emacs is not finding helm-org

I don't disagree to your judgement. However, the identical configuration is working with other emacs versions. Maybe the issue is related to the snapshot character of the binary.
