### ISSUE TITLE
Show headings with parents as breadcrumbs

### ISSUE THREAD

**Issue by FrostyX** [emacs-helm/helm-org#27]
I have a kilometer long Org document with headings like so

```org
* Knowledge
** Emacs
** Fedora
** Qtile

* Things to do
** Things to code
*** Emacs
*** Qtile
```

When I run `M-x helm-org-in-buffer-headings` and start searching for example "Emacs", I can see two rows in Helm

```org
** Emacs
*** Emacs
```

I have a lot of _duplicities_ like this (e.g. in the case of Emacs, 5 different headings), and I am never really sure which one I am jumping to. It would be amazing if `M-x helm-org-in-buffer-headings` (or some other command) could print something like this

```
Knowledge / Emacs
Things to do / Emacs
```

**Comment by rbenson** [comment]
Set `helm-org-format-outline-path` to `t`

**Comment by FrostyX** [comment]
Perfect, I didn't know about this option.
Thank you very much
