### ISSUE TITLE
helm-org-in-buffer-headings signals repeating org-indent error

### ISSUE THREAD

**Issue by progfolio** [emacs-helm/helm-org#28]
`helm-org-in-buffer-headings` signals the following warning in a repeated idle timer (due to the way org-ident watches org-indent-agentized-buffers): 

```emacs-lisp
org-element-at-point: ‘org-element-at-point’ cannot be used in non-Org buffer #<buffer *helm org inbuffer*> (helm-major-mode)
```

Relevant code in `helm-org-indent-headings-1`:

https://github.com/emacs-helm/helm-org/blob/d67186d3a64e610c03a5f3d583488f018fb032e4/helm-org.el#L352-L359

Org mode version 9.7-pre (9.7-pre-n/a-g63e8ca @ /home/n/.emacs.d/elpaca/builds/org/)
helm-org @ commit:  d67186d

**Comment by thierryvolpiatto** [comment]
Hello, sorry for late reply on this.
I have tried on Emacs-30 and it is working fine, I guess it is a regression in org itself (latest) and IMO should be reported upstream.
