### ISSUE TITLE
Circular dependency

### ISSUE THREAD

**Issue by malb** [emacs-helm/helm-org#8]
With https://github.com/emacs-helm/helm/issues/2185 `helm` now depends on `helm-org` and `helm-org` depends on `helm`. The ensuing recursion hits `max-lisp-eval-depth` and installation fails.

**Comment by Compro-Prasad** [comment]
Very Important Issue. But this is a problem with `helm` and not `helm-org`. `helm` shouldn't be dependant upon `helm-org`.

**Comment by thierryvolpiatto** [comment]
Martin Albrecht <notifications@github.com> writes:

> With emacs-helm/helm#2185 helm-org now depends on helm and helm
> depends on helm-org. The ensuing recursion hits max-lisp-eval-depth
> and installation fails.

Of course, fixed now, thanks.

> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or mute the thread.*


--
Thierry

Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997
